In [1]:
import numpy as np

In [2]:
arr = np.array([134, 27, 30, 4.90, 5])
print(arr.dtype)

float64


In [3]:
arr = np.array(['abc', "ab", 'dfe', 'kl'])
print(arr.dtype)

<U3


In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
print(np.__version__)

1.21.5


In [6]:
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy
arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [8]:
import numpy as np
arr = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


In [9]:
import numpy as np
arr = np.array(42)
print(arr)

42


In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [11]:
import numpy as np
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [14]:
import numpy as np
arr = np.array([1,2,3,4,], ndmin=5)
print(arr)
print('number of diamensions:',arr.ndim)

[[[[[1 2 3 4]]]]]
number of diamensions: 5


In [15]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5])
#print(arr[-2:-1:2])
print(arr[1:6:2])

[2 4]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr)
print('shape of array:', arr.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
shape of array: (12,)


In [17]:
arr = arr.reshape(3, 2 , 2)
arr

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [18]:
arr = arr.reshape(6, 2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# iterate array

In [19]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [23]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])

arr=np.ones(shape=(3,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [24]:
arr=np.zeros(shape=(3,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [25]:
arr=np.array([[1,2,3],[4,5,6]])
arr = np.zeros_like(arr)
print(arr)


[[0 0 0]
 [0 0 0]]


In [26]:
arr = np.random.randint(3,size=10)
print(arr)

[0 0 0 2 1 2 1 1 1 0]


In [27]:
arr = np.arange(1, 10, 16)
arr = np.reshape(4,4)
print(arr)

ValueError: cannot reshape array of size 1 into shape (4,)

In [28]:
arr = np.linspace(1, 10, 16)
arr = arr.reshape(4,4)
print(arr)

[[ 1.   1.6  2.2  2.8]
 [ 3.4  4.   4.6  5.2]
 [ 5.8  6.4  7.   7.6]
 [ 8.2  8.8  9.4 10. ]]


In [29]:
arr = np.full((4,4),5)
print(arr)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [30]:
arr = np.eye(6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [31]:
arr = np.empty((4,4))
print(arr)

[[ 1.   1.6  2.2  2.8]
 [ 3.4  4.   4.6  5.2]
 [ 5.8  6.4  7.   7.6]
 [ 8.2  8.8  9.4 10. ]]


# data type 

In [33]:
import numpy as np
arr = np.array([11,22,33])

print(arr.dtype)

int32


In [34]:
arr = np.array([2.0 + 6.5j, 4.5 + 7.8j, 7.0 + 8.6j])
print(arr.dtype)


complex128


In [35]:
arr = np.array([1, 0.5,"hello", None, True, False,'a'], dtype=bool)
print(arr)

[ True  True  True False  True False  True]


In [36]:
arr = np.array([17,11,"date","month"]) ##object

print(type(arr))

<class 'numpy.ndarray'>


In [37]:
arr = np.array(['abc', 'xyz'])
print(arr)

print(arr.dtype)

['abc' 'xyz']
<U3


# Inspecting Your Array

In [39]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

arr.shape

(2, 3)

In [40]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
len(arr)

2

In [41]:
arr = np.array([11,17,25,4,7], ndmin=32)

arr


array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[11,
                                      17,
                                      25,
                                       4,
                                       7]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [42]:
arr = np.array([[1, 2, 3,4], [4, 5, 6,7]])
arr.size

8

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)

(2, 3)


In [44]:
print(np.dtype(np.int16))  ##datatype


int16


In [46]:
import numpy as np
a = np.array([-.05, 0, 0])
b = np.array([-3, -3, -3])
c = a-b
c = np.subtract(a, b)
print(c)

[2.95 3.   3.  ]


In [47]:
a = np.array([2.5, 4, 6])
b = np.array([5, 7, 9])
c = b+a
c = np.add(b, a)
print(c)

[ 7.5 11.  15. ]


In [48]:
a = np.array([0.66666667, 1, 1])
b = np.array([0.25, 0.4, 0.5])
c = a/b
c = np.divide(a,b)
print(c)

[2.66666668 2.5        2.        ]


In [49]:
a = np.array([1.5, 4, 9])
b = np.array([4, 10, 18])
c = a*b
c = np.multiply(a,b)
print(c)

[  6.  40. 162.]


In [50]:
a = np.array([2, 4, 9])
b = np.exp(a)
print(b)

[7.38905610e+00 5.45981500e+01 8.10308393e+03]


In [51]:
a = np.array([2, 4, 9])
b = np.sqrt(a)
print(b)

[1.41421356 2.         3.        ]


In [52]:
a = np.array([0, 45, 90])
b = np.sin(a)
print(b)

[0.         0.85090352 0.89399666]


In [53]:
a = np.array([0, 45, 90])
b = np.cos(a)
print(b)



[ 1.          0.52532199 -0.44807362]


In [54]:
a = np.array([1, 4, 6])
b = np.log(a)
print(b)

[0.         1.38629436 1.79175947]


# Subsetting Slicing Indexing

In [55]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[4])

5


In [56]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1,2])

6


In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[0:2])

[1 2]


In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[0:2,1])

[2 5]


In [59]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[:1])

[[1 2 3]]


In [60]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7,8,9]]])
print(arr[0:1,:])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [61]:
arr = np.array([[[1, 2, 3], [4, 5, 6], [7,8,9]]])
print(arr[0:1,:])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
