 # Array Mathematics


In [1]:
import numpy as np

In [2]:
A=np.array([[1, 2], [5, 6]])
A

array([[1, 2],
       [5, 6]])

In [3]:
B=np.array([[1, 4], [5, 7]])
print(B)

[[1 4]
 [5 7]]


In [4]:
A+B

array([[ 2,  6],
       [10, 13]])

In [5]:
A-B

array([[ 0, -2],
       [ 0, -1]])

In [6]:
A*B

array([[ 1,  8],
       [25, 42]])

In [7]:
A/B

array([[1.        , 0.5       ],
       [1.        , 0.85714286]])

In [8]:
A+6

array([[ 7,  8],
       [11, 12]])

In [9]:
A-6

array([[-5, -4],
       [-1,  0]])

In [10]:
A*6

array([[ 6, 12],
       [30, 36]])

In [11]:
A/6

array([[0.16666667, 0.33333333],
       [0.83333333, 1.        ]])

In [12]:
A=np.array([[1, 2], [5, 6]])
np.exp(A)

array([[  2.71828183,   7.3890561 ],
       [148.4131591 , 403.42879349]])

In [13]:
A=np.array([[1, 2], [5, 6]])

np.sqrt(A)


array([[1.        , 1.41421356],
       [2.23606798, 2.44948974]])

In [14]:
A=np.array([[0, 1, 30, 45, 90]])
np.sin(A)

array([[ 0.        ,  0.84147098, -0.98803162,  0.85090352,  0.89399666]])

In [15]:
A=np.array([[0, 1, 30, 45, 90]])
np.cos(A)

array([[ 1.        ,  0.54030231,  0.15425145,  0.52532199, -0.44807362]])

In [16]:
A=np.array([[1, 2, 3, 4, 5]])
np.log(A)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791]])

In [17]:
A=np.array([[8, 7], [5, 7]])
B=np.array([[5, 8], [9, 7]])

np.dot(A,B)

array([[103, 113],
       [ 88,  89]])

# Comparison

In [18]:
import numpy as np

In [19]:
A=np.array([[1, 2], [5, 6]])
print(A)

[[1 2]
 [5 6]]


In [20]:
B=np.array([[1, 4], [5, 7]])

print(B)


[[1 4]
 [5 7]]


In [21]:
A==B

array([[ True, False],
       [ True, False]])

In [22]:
A<2

array([[ True, False],
       [False, False]])

In [23]:
A>5

array([[False, False],
       [False,  True]])

In [24]:
np.array_equal(A, B)

False

In [25]:
A[A==B]

array([1, 5])

# Aggregate Function

In [26]:
A=np.array([[1, 2], [5, 6]])
np.sum(A)

14

In [27]:
A=np.array([[1, 2], [5, 6]])
np.min(A)

1

In [28]:
A=np.array([[1, 2], [5, 6]])
np.max(A)

6

In [29]:
A.max(axis=0)

array([5, 6])

In [30]:
np.cumsum(A)

array([ 1,  3,  8, 14], dtype=int32)

In [31]:
A.cumsum(axis=1)

array([[ 1,  3],
       [ 5, 11]], dtype=int32)

In [32]:
np.mean(A)

3.5

In [33]:
np.median(A)

3.5

In [34]:
np.corrcoef(A)

array([[1., 1.],
       [1., 1.]])

In [35]:
np.std(A)

2.0615528128088303

# Copying array

In [36]:
import numpy as np
A=np.array([[1, 2], [5, 6]])

B=A.view()
print(A)


[[1 2]
 [5 6]]


In [37]:
np.copy(B)

array([[1, 2],
       [5, 6]])

In [38]:
arr = np.array([1, 2, 3, 4])
x = arr.copy()
arr[3] = 5
print(arr)

[1 2 3 5]


# Sorting

In [39]:
import numpy as np
arr = ([17, 11, 25, 4, 7])
arr.sort()
print(arr)

[4, 7, 11, 17, 25]


In [40]:
A=np.array([[7, 2], [45, 35]])
A.sort(axis=1)
print(A)

[[ 2  7]
 [35 45]]


# Subsetting

In [41]:
import numpy as np
arr = np.array([25, 4, 7, 17, 11])
print(arr[3])

17


In [42]:
arr = np.array([[25, 4, 7], [17, 11, 13]])
print(arr[1,0])

17


# Slicing

In [43]:
import numpy as np
arr = np.array([25, 4, 7, 17, 11])
arr[2:3]

array([7])

In [44]:
arr = np.array([[25, 4, 7], [17, 11, 13]])

print(arr[0:1])     ###can't understand

[[25  4  7]]


In [45]:
arr = np.array([[25, 4, 7], [17, 11, 13]])
print(arr[:1])
## :0 than []
## :1 than [25, 4, 7]
## :2 than both rows... i want only 2nd row

[[25  4  7]]


In [46]:
arr = np.array([[25, 4, 7], [17, 11, 13]])
print(arr[1,...])

[17 11 13]


In [47]:
arr = np.array([[25, 4, 7], [17, 11, 13]])
print(arr[::-1])

[[17 11 13]
 [25  4  7]]


# Boolean Indexing

In [48]:
import numpy as np
arr = np.array([25, 4, 7, 17, 11])
print(arr[arr<10])
print(arr[arr>15])


[4 7]
[25 17]


# Fancy Indexing

In [49]:
arr = np.array([[25, 4, 7, 9], [17, 11, 13, 22]])
arr[[1, 0, 1, 0], [0, 1, 2, 0]]
print(arr)


[[25  4  7  9]
 [17 11 13 22]]


# Array Manipulation 


## Transposing Array

In [50]:
import numpy as np
a=np.arange(6).reshape((2,3))
a
b=np.transpose(a)
b

array([[0, 3],
       [1, 4],
       [2, 5]])

In [51]:
    a = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
    print(a, end = '\n\n')
    a.T

[[1 2 3]
 [4 5 6]
 [7 8 9]]



array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Changing Array Shape 

In [52]:
arr = np.array([[25, 4, 7, 9], [17, 11, 13, 22]])
print(arr.ravel())

[25  4  7  9 17 11 13 22]


In [53]:
arr = np.array([[25, 4, 7, 9], [17, 11, 13, 22]])
print(arr.reshape(4,-3))

[[25  4]
 [ 7  9]
 [17 11]
 [13 22]]


## Adding/removing shape

In [54]:
arr = np.array([[[25, 4, 7, 9], [17, 11, 13, 22], [77, 88, 99, 55]]])
print(arr.resize(4,3))
print(arr)

None
[[25  4  7]
 [ 9 17 11]
 [13 22 77]
 [88 99 55]]


In [55]:
np.append ([0, 1, 2], [[3, 4, 5], [6, 7, 8]])
np.append([[0, 1, 2], [3, 4, 5]],[[6, 7, 8]], axis=0)
    


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Spliting Arrays

In [57]:
arr = np.array([[[25, 4, 7, 9], [22, 24, 26, 28], [33, 36, 39, 31]]])

np.hsplit(arr,3)


[array([[[25,  4,  7,  9]]]),
 array([[[22, 24, 26, 28]]]),
 array([[[33, 36, 39, 31]]])]

In [58]:
arr = np.array([[[25, 4, 7, 9], [22, 24, 26, 28], [33, 36, 39, 31]]])

np.vsplit(arr,1)


[array([[[25,  4,  7,  9],
         [22, 24, 26, 28],
         [33, 36, 39, 31]]])]

In [59]:
#### delete dimention

a = np.arange(9).reshape(1, 3, 1, 3, 1)
a.shape

sq = np.squeeze(a)
sq
sq.shape

(3, 3)

In [60]:
### addind dimention

a = np.arange(9).reshape(3,3)
(a[np.newaxis].shape)

(1, 3, 3)

In [61]:
### append

a1 = np.array([1, 2, 4, 5, 6])
a2 = np.append(a1, 7)

print("Orignal Array:", a1)
print("New Array:", a2)

Orignal Array: [1 2 4 5 6]
New Array: [1 2 4 5 6 7]


In [62]:
### delete


a = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
index = [2, 5, 7]
a1 = np.delete(a, index)
a1



array([10, 11, 13, 14, 16, 18, 19, 20])

In [63]:
## insert

a = np.array([[0, 0], [1, 1], [2, 2]])
a
np.insert(a,2, 3 )

array([0, 0, 3, 1, 1, 2, 2])

In [64]:
a = np.array([[0, 0], [1, 1], [2, 2]])
np.insert(a, 2, 3, axis = 1)

array([[0, 0, 3],
       [1, 1, 3],
       [2, 2, 3]])

In [65]:
a = np.array([[0, 0], [1, 1], [2, 2]])
b = a.ravel()
b

array([0, 0, 1, 1, 2, 2])